### model
model_name_or_path: HuggingFaceTB/SmolLM-135M

### method
stage: sft
do_train: true
finetuning_type: full

### dataset
dataset: massive_train_slot
template: default
cutoff_len: 256
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/smollm_135m
logging_steps: 250
save_steps: 4000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
